// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cmo, use-js-string=true, version=5.5.2

//# unitInfo: Provides: Dune__exe__Prooftree
//# unitInfo: Requires: Dune__exe__Rules, Line, Stdlib__Hashtbl
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) == 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   function caml_call3(f, a0, a1, a2){
    return (f.l >= 0 ? f.l : f.l = f.length) == 3
            ? f(a0, a1, a2)
            : runtime.caml_call_gen(f, [a0, a1, a2]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    Stdlib_Hashtbl = global_data.Stdlib__Hashtbl,
    Dune_exe_Rules = global_data.Dune__exe__Rules,
    Line = global_data.Line,
    lines = caml_call2(Stdlib_Hashtbl[1], 0, 40);
   function replace_line(linenum, s){
    var line = caml_call1(Line[9], s);
    caml_call3(Stdlib_Hashtbl[11], lines, linenum, line);
    return caml_call2(Dune_exe_Rules[1], lines, line);
   }
   function delete_line(linenum){
    caml_call2(Stdlib_Hashtbl[10], lines, linenum);
    return caml_call1(Dune_exe_Rules[2], lines);
   }
   var Dune_exe_Prooftree = [0, lines, replace_line, delete_line];
   runtime.caml_register_global(3, Dune_exe_Prooftree, "Dune__exe__Prooftree");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIubWFpbi5lb2Jqcy9qc29vL2R1bmVfX2V4ZV9fUHJvb2Z0cmVlLmNtby5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6WyJsaW5lcyIsInJlcGxhY2VfbGluZSIsImxpbmVudW0iLCJzIiwibGluZSIsImRlbGV0ZV9saW5lIl0sInNvdXJjZXMiOlsiL3dvcmtzcGFjZV9yb290L2pzL3Byb29mdHJlZS5tbCJdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7O0c7Ozs7O0c7Ozs7O0c7Ozs7O0dBQXNDOzs7OztJQUFsQ0EsUUFBa0M7WUFFbENDLGFBQWNDLFNBQWdCQztJQUNyQixJQUFQQyxPQUFPLG9CQURxQkQ7SUFFaEMsK0JBSkVILE9BRWNFLFNBQ1pFO0lBQ0osT0FBQSw4QkFKRUosT0FHRUk7R0FFcUI7WUFFdkJDLFlBQWFIO0lBQ2YsK0JBUkVGLE9BT2FFO3lDQVBiRjtHQVNtQjtnQ0FUbkJBLE9BRUFDLGNBS0FJOzs7RSIsInNvdXJjZXNDb250ZW50IjpbImxldCBsaW5lcyA6IChpbnQsIExpbmUudCkgSGFzaHRibC50ID0gSGFzaHRibC5jcmVhdGUgNDBcblxubGV0IHJlcGxhY2VfbGluZSAobGluZW51bSA6IGludCkgKHMgOiBzdHJpbmcpIDogYm9vbCA9XG4gIGxldCBsaW5lID0gTGluZS5pbnRlcnAgcyBpblxuICBIYXNodGJsLnJlcGxhY2UgbGluZXMgbGluZW51bSBsaW5lIDtcbiAgUnVsZXMuaXNfdmFsaWQgbGluZXMgbGluZSBcblxubGV0IGRlbGV0ZV9saW5lIChsaW5lbnVtIDogaW50KSA6IGJvb2wgPVxuICBIYXNodGJsLnJlbW92ZSBsaW5lcyBsaW5lbnVtIDtcbiAgUnVsZXMuYWxsX3ZhbGlkIGxpbmVzXG4iXX0=
