// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cmo, use-js-string=true, version=5.5.2

//# unitInfo: Provides: Dune__exe__Main
//# unitInfo: Requires: CamlinternalOO, Interp__Main, Js_of_ocaml__Js
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    caml_js_wrap_meth_callback = runtime.caml_js_wrap_meth_callback;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) == 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    Interp_Main = global_data.Interp__Main;
   global_data.CamlinternalOO;
   var
    Js_of_ocaml_Js = global_data.Js_of_ocaml__Js,
    cst_Interpreter = "Interpreter";
   function t3(param, s){return caml_call1(Interp_Main[6], s);}
   function t2(param, s){return caml_call1(Interp_Main[1], s);}
   caml_call2
    (Js_of_ocaml_Js[50],
     cst_Interpreter,
     {parse: caml_js_wrap_meth_callback(t2),
      interp: caml_js_wrap_meth_callback(t3)});
   var Dune_exe_Main = [0];
   runtime.caml_register_global(9, Dune_exe_Main, "Dune__exe__Main");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIubWFpbi5lb2Jqcy9qc29vL2R1bmVfX2V4ZV9fTWFpbi5jbW8uanMiLCJzb3VyY2VSb290IjoiIiwibmFtZXMiOlsicyJdLCJzb3VyY2VzIjpbIi93b3Jrc3BhY2Vfcm9vdC9qcy9tYWluLm1sIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7OztHOzs7OztHOzs7Ozs7Ozs7Ozs7c0JBT3FCQSxHQUFJLE9BQUEsMkJBQUpBLEdBQXdCO3NCQUZ6QkEsR0FBSSxPQUFBLDJCQUFKQSxHQUF1QjtHQUZ6Qzs7Ozs7R0FBQTs7O0UiLCJzb3VyY2VzQ29udGVudCI6WyJvcGVuIEpzX29mX29jYW1sXG5cbmxldCBfID1cbiAgSnMuZXhwb3J0IFwiSW50ZXJwcmV0ZXJcIlxuICAgIChvYmplY3QlanNcbiAgICAgICBtZXRob2QgcGFyc2UgcyA9IEludGVycC5NYWluLnBhcnNlIHNcblxuICAgICAgIG1ldGhvZCBpbnRlcnAgcyA9IEludGVycC5NYWluLmludGVycCBzXG4gICAgZW5kIClcbiJdfQ==
